name: Unit Tests

on:
  push:
    branches: [main]
    paths: ["client/**"]
  pull_request:
    branches: [main]
    paths: ["client/**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test
